### ISSUE TITLE
Chức năng Register

### ISSUE THREAD

**Issue by LeHang01** [LeHang01/QuanLyHoSoSinhVien#4]
1. Tách branch từ Devloper để thực hiện code chức năng.
2. Đặt tên branch là "Feature-register"
3. Bao gồm Họ tên đầy đủ, mật khẩu, ngày sinh, email, quê quán
4. email phải có @dau.edu.vn
5. Password phải >= 8 ký tự (nếu nhỏ hơn thì thông báo ở phía dưới ô nhập password)
6. Nếu thông tin đăng kí là đúng thì chuyển đến trang "Login" (nếu sai thì hiển thị alert thông báo lỗi)
7. Giao diện trang register có thể tương tự như hình bên dưới:
![registration-forms](https://github.com/lethihang2001wscfer/QuanLyHoSoSinhVien/assets/127541929/9d745ddb-72dc-4bf6-8be3-8cd21095f830)

**Comment by LoiDT02** [comment]
Đã hoàn thành
