### ISSUE TITLE
Chức năng Add thông tin sinh viên

### ISSUE THREAD

**Issue by LeHang01** [LeHang01/QuanLyHoSoSinhVien#5]
1. Tách branch từ Devloper để thực hiện code chức năng.
2. Đặt tên branch là "Feature-Add"
3. Thêm các thông tin như ảnh, tên, tuổi, lớp, khóa học, thành tích
Nếu thông tin thêm đầy đủ và đúng thì chuyển đến trang "Home" (nếu sai thì hiển thịf alert thông báo lỗi)

**Comment by th21202** [comment]
Đã hoàn thành
